config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'

  get 'punto2/modp'
  post 'punto2/modp'

  resources :detalles
  resources :multa
  resources :prestamos
  resources :usuarios
  resources :libros
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/detalle.rb
class Detalle < ApplicationRecord
  belongs_to :Prestamo
  belongs_to :Libro
end

app/controllers/detalles_controller.rb
class DetallesController < ApplicationController
  before_action :set_detalle, only: %i[ show edit update destroy ]

  # GET /detalles or /detalles.json
  def index
    @detalles = Detalle.all
  end

  # GET /detalles/1 or /detalles/1.json
  def show
  end

  # GET /detalles/new
  def new
    @detalle = Detalle.new
  end

  # GET /detalles/1/edit
  def edit
  end

  # POST /detalles or /detalles.json
  def create
    @detalle = Detalle.new(detalle_params)

    respond_to do |format|
      if @detalle.save
        format.html { redirect_to detalle_url(@detalle), notice: "Detalle was successfully created." }
        format.json { render :show, status: :created, location: @detalle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalles/1 or /detalles/1.json
  def update
    respond_to do |format|
      if @detalle.update(detalle_params)
        format.html { redirect_to detalle_url(@detalle), notice: "Detalle was successfully updated." }
        format.json { render :show, status: :ok, location: @detalle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalles/1 or /detalles/1.json
  def destroy
    @detalle.destroy

    respond_to do |format|
      format.html { redirect_to detalles_url, notice: "Detalle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalle
      @detalle = Detalle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detalle_params
      params.require(:detalle).permit(:cantidad, :Prestamo_id, :Libro_id)
    end
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/views/detalles/_detalle.html.erb
<div id="<%= dom_id detalle %>">
 
<tr>

        <td>
        <%= detalle.cantidad %>
        </td>

        <td>
        <%= detalle.Prestamo_id.to_s + " - Realizado por " +
        detalle.Prestamo.Usuario.nombres + " " +
        detalle.Prestamo.Usuario.apellidos + " en " +
        detalle.Prestamo.fecha.to_s  %>
        </td>

        <td>
        <%= detalle.Libro_id.to_s + " - " +
        detalle.Libro.titulo + " en " +
        detalle.Libro.anyo.to_s %>
        </td>


        <td>
        
        <%= link_to "Editar", edit_detalle_path(detalle) , :class => "btn btn-primary"%> 
        
        </td>
        
        <td>
        
        <%= button_to "Eliminar", detalle, method: :delete, data: {confirm: 'Are you sure?' }, :class => "btn btn-danger"%>

        </td>
</tr>



</div>

app/views/detalles/_form.html.erb
<%= form_with(model: detalle) do |form| %>
  <% if detalle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(detalle.errors.count, "error") %> prohibited this detalle from being saved:</h2>

      <ul>
        <% detalle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cantidad, style: "display: block" %>
    <%= form.number_field :cantidad %>
  </div>

  <div>
  Prestamo:
  <br>
  <%= form.select :Prestamo_id, options_for_select(Prestamo.all.map{|s| [s.id.to_s + " - Realizado por " + s.Usuario.nombres + " " + s.Usuario.apellidos + " en " + s.fecha.to_s, s.id]}) %>
  </div>
  <br>
 
  <div>
  Libro:
  <br>
  <%= form.select :Libro_id, options_for_select(Libro.all.map{|s| [s.id.to_s + " - " + s.titulo + " por " + s.autor + " en " + s.anyo.to_s, s.id]}) %>
  </div>
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/detalles/edit.html.erb
<h1>Editing detalle</h1>

<%= render "form", detalle: @detalle %>

<br>

<div>
  <%= link_to "Show this detalle", @detalle %> |
  <%= link_to "Back to detalles", detalles_path %>
</div>

app/views/detalles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Detalles</h1>
<br>

<%= link_to "Nuevo detalle", new_detalle_path, :class => "btn btn-success" %>



<br><br><br>

<div id="detalles">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Cantidad</th>
      <th scope="col">Prestamo</th>
      <th scope="col">Libro</th>
      <th scope="col"> </th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
  <% @detalles.each do |detalle| %>
    <%= render detalle %>
    
    <% end %>
    

  </tbody>
</table>

  
</div>

<br>

app/views/detalles/new.html.erb
<h1>New detalle</h1>

<%= render "form", detalle: @detalle %>

<br>

<div>
  <%= link_to "Back to detalles", detalles_path %>
</div>

app/views/detalles/show.html.erb
<p style="color: green"><%= notice %></p>



<h3>Listar Detalle</h3>


<p>
<strong>ID: </strong>
<%= @detalle.id%>
</p>

<p>
<strong>Cantidad: </strong>
<%= @detalle.cantidad%>
</p>

<p>
<strong>Prestamo: </strong>
<%= @detalle.Prestamo_id.to_s + " - Realizado por " +
@detalle.Prestamo.Usuario.nombres + " " +
@detalle.Prestamo.Usuario.apellidos + " en " +
@detalle.Prestamo.fecha.to_s  %>
</p>

<p>
<strong>Libro: </strong>
<%= @detalle.Libro_id.to_s + " - " +
@detalle.Libro.titulo + " en " +
@detalle.Libro.anyo.to_s %>
</p>


<div>
 
  <%= link_to "Back to detalles", detalles_path %>

  
</div>