config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'

  get 'punto2/modp'
  post 'punto2/modp'

  resources :detalles
  resources :multa
  resources :prestamos
  resources :usuarios
  resources :libros
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def consulta
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%= link_to 'Inicio', root_path, class: "navbar-brand" %>
  

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      
      <%= link_to 'Modulo de Prestamos', punto2_modp_path, class: "nav-link" %>
     
      
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<p>Taller de Soporte de Ingeniería</p>
<br>
<article> Presentado por: De La Rosa Adrian, Gutierrez Juan y Perez Ariel</article>

<br><br>

<h3>Administración de Datos</h3>

<br>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Tablas</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= link_to 'Libros', libros_path%></th>
      
    </tr>
    <tr>
    <th scope="row"><%= link_to 'Usuarios', usuarios_path%></th>
    </tr>
    <tr>
    <th scope="row"><%= link_to 'Prestamos', prestamos_path%></th>
    </tr>
    <tr>
    <th scope="row"><%= link_to 'Detalles', detalles_path%></th>
  </tr>
  <tr>
  <th scope="row"><%= link_to 'Multas', multa_path%></th>
    </tr>
  </tbody>
</table>