config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'

  get 'punto2/modp'
  post 'punto2/modp'

  resources :detalles
  resources :multa
  resources :prestamos
  resources :usuarios
  resources :libros
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/prestamo.rb
class Prestamo < ApplicationRecord
  belongs_to :Usuario
end

app/controllers/prestamos_controller.rb
class PrestamosController < ApplicationController
  before_action :set_prestamo, only: %i[ show edit update destroy ]

  # GET /prestamos or /prestamos.json
  def index
    @prestamos = Prestamo.all
  end

  # GET /prestamos/1 or /prestamos/1.json
  def show
  end

  # GET /prestamos/new
  def new
    @prestamo = Prestamo.new
  end

  # GET /prestamos/1/edit
  def edit
  end

  # POST /prestamos or /prestamos.json
  def create
    @prestamo = Prestamo.new(prestamo_params)

    respond_to do |format|
      if @prestamo.save
        format.html { redirect_to prestamo_url(@prestamo), notice: "Prestamo was successfully created." }
        format.json { render :show, status: :created, location: @prestamo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prestamos/1 or /prestamos/1.json
  def update
    respond_to do |format|
      if @prestamo.update(prestamo_params)
        format.html { redirect_to prestamo_url(@prestamo), notice: "Prestamo was successfully updated." }
        format.json { render :show, status: :ok, location: @prestamo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestamos/1 or /prestamos/1.json
  def destroy
    @prestamo.destroy

    respond_to do |format|
      format.html { redirect_to prestamos_url, notice: "Prestamo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prestamo
      @prestamo = Prestamo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prestamo_params
      params.require(:prestamo).permit(:fecha, :estado, :Usuario_id)
    end
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/views/prestamos/_form.html.erb
<%= form_with(model: prestamo) do |form| %>
  <% if prestamo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prestamo.errors.count, "error") %> prohibited this prestamo from being saved:</h2>

      <ul>
        <% prestamo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.check_box :estado %>
  </div>

  <div>
    Usuario:
    <br>
    <%= form.select :Usuario_id, options_for_select(Usuario.all.map{|s| [s.id.to_s + " - " + s.nombres + " " + s.apellidos, s.id]}) %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prestamos/_prestamo.html.erb
<div id="<%= dom_id prestamo %>">

<tr>

        <td>
        <%= prestamo.fecha %>
        </td>

        <td>
        <%= prestamo.estado %>
        </td>

        <td>
        <%= prestamo.Usuario_id.to_s + " - " + prestamo.Usuario.nombres + " " + prestamo.Usuario.apellidos%>

        </td>

        <td>
        
        <%= link_to "Editar", edit_prestamo_path(prestamo) , :class => "btn btn-primary"%> 
        
        </td>
        
        <td>
        
        <%= button_to "Eliminar", prestamo, method: :delete, data: {confirm: 'Are you sure?' }, :class => "btn btn-danger"%>

        </td>
</tr>




</div>

app/views/prestamos/edit.html.erb
<h1>Editing prestamo</h1>

<%= render "form", prestamo: @prestamo %>

<br>

<div>
  <%= link_to "Show this prestamo", @prestamo %> |
  <%= link_to "Back to prestamos", prestamos_path %>
</div>

app/views/prestamos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Prestamos</h1>

<br>

<%= link_to "Nuevo prestamo", new_prestamo_path, :class => "btn btn-success" %>



<br><br><br>

<br>
<div id="prestamos">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Fecha</th>
      <th scope="col">Estado</th>
      <th scope="col">Usuario</th>
      <th scope="col"> </th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
  <% @prestamos.each do |prestamo| %>
    <%= render prestamo %>
    
    <% end %>
    

  </tbody>
</table>

  
</div>

<br>

app/views/prestamos/new.html.erb
<h1>New prestamo</h1>

<%= render "form", prestamo: @prestamo %>

<br>

<div>
  <%= link_to "Back to prestamos", prestamos_path %>
</div>

app/views/prestamos/show.html.erb
<p style="color: green"><%= notice %></p>

<h3>Listar Prestamo</h3>


<p>
<strong>ID: </strong>
<%= @prestamo.id%>
</p>


<p>
<strong>Estado: </strong>
<%= @prestamo.estado%>
</p>

<p>
<strong>Usuario: </strong>
<%= @prestamo.Usuario.nombres + " " + @prestamo.Usuario.apellidos %>
</p>

<br>

<div>
 
  <%= link_to "Back to prestamos", prestamos_path %>

</div>