config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'

  get 'punto2/modp'
  post 'punto2/modp'

  resources :detalles
  resources :multa
  resources :prestamos
  resources :usuarios
  resources :libros
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: %i[ show edit update destroy ]

  # GET /libros or /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1 or /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros or /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to libro_url(@libro), notice: "Libro was successfully created." }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1 or /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to libro_url(@libro), notice: "Libro was successfully updated." }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1 or /libros/1.json
  def destroy
    @libro.destroy

    respond_to do |format|
      format.html { redirect_to libros_url, notice: "Libro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def libro_params
      params.require(:libro).permit(:titulo, :autor, :anyo)
    end
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.erb
<%= form_with(model: libro) do |form| %>
  <% if libro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
        <% libro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :autor, style: "display: block" %>
    <%= form.text_field :autor %>
  </div>

  <div>
    <%= form.label :anyo, style: "display: block" %>
    <%= form.number_field :anyo %>
  </div>

  <br>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/libros/_libro.html.erb
<div id="<%= dom_id libro %>">

<tr>
        <td>
        <%= libro.titulo %>
        </td>

        <td>
        <%= libro.autor %>
        </td>

        <td>
        <%= libro.anyo %>
        </td>


        <td>
        
        <%= link_to "Editar", edit_libro_path(libro) , :class => "btn btn-primary"%> 
        
        </td>
        
        <td>
        
        <%= button_to "Eliminar", libro, method: :delete, data: {confirm: 'Are you sure?' }, :class => "btn btn-danger"%>

        </td>

      
    </tr>

</div>

app/views/libros/edit.html.erb
<h1>Editing libro</h1>

<%= render "form", libro: @libro %>

<br>
<br>

<div>
  <%= link_to "Listar Libro", @libro %> |
  <%= link_to "Atras", libros_path %>
</div>

app/views/libros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Libros</h1>

<br>


<div id="libros">

<%= link_to "Nuevo Libro", new_libro_path, :class => "btn btn-success" %>



<br><br><br>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Titulo</th>
      <th scope="col">Autor</th>
      <th scope="col">Año</th>
      <th scope="col"> </th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
  <% @libros.each do |libro| %>

    <%= render libro %>
    
    <% end %>
    

  </tbody>
</table>

  
</div>

<br>

app/views/libros/new.html.erb
<h1>New libro</h1>

<%= render "form", libro: @libro %>

<br>

<div>
  <%= link_to "Back to libros", libros_path %>
</div>

app/views/libros/show.html.erb
<p style="color: green"><%= notice %></p>

<h3>Listar Libro</h3>


<p>
<strong>ID: </strong>
<%= @libro.id%>
</p>


<p>
<strong>Titulo: </strong>
<%= @libro.titulo%>
</p>

<p>
<strong>Autor: </strong>
<%= @libro.autor%>
</p>


<p>
<strong>Año: </strong>
<%= @libro.anyo%>
</p>


<div>

  <%= link_to "Back to libros", libros_path %>

  
</div>